In [2]:
import sys
print(sys.executable)

/home/nilima/Desktop/portfolio/probabilistic-energy-forecasting-ML/.venv/bin/python

In [6]:
pip list | grep seaborn

seaborn            0.13.2
Note: you may need to restart the kernel to use updated packages.

In [10]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the dataset
raw_data_consumption = pd.read_csv('/home/nilima/Desktop/portfolio/probabilistic-energy-forecasting-ML/raw_data/Actual_consumption_202403010000_202603020000_Hour.csv', sep=";")

In [ ]:
display(raw_data_consumption.head())

,Start date,End date,grid load [MWh] Calculated resolutions,Grid load incl. hydro pumped storage [MWh] Calculated resolutions,Hydro pumped storage [MWh] Calculated resolutions,Residual load [MWh] Calculated resolutions
0,"Mar 1, 2024 12:00 AM","Mar 1, 2024 1:00 AM","49,611.50","51,275.50","1,664.00","28,610.50"
1,"Mar 1, 2024 1:00 AM","Mar 1, 2024 2:00 AM","48,075.75","50,337.00","2,261.25","27,862.75"
2,"Mar 1, 2024 2:00 AM","Mar 1, 2024 3:00 AM","47,663.00","51,471.00","3,808.00","27,326.25"
3,"Mar 1, 2024 3:00 AM","Mar 1, 2024 4:00 AM","48,234.00","52,043.75","3,809.75","27,592.75"
4,"Mar 1, 2024 4:00 AM","Mar 1, 2024 5:00 AM","49,060.50","51,579.25","2,518.75","28,203.00"

In [13]:
print(raw_data_consumption.columns)

Index(['Start date', 'End date', 'grid load [MWh] Calculated resolutions',
       'Grid load incl. hydro pumped storage [MWh] Calculated resolutions',
       'Hydro pumped storage [MWh] Calculated resolutions',
       'Residual load [MWh] Calculated resolutions'],
      dtype='object')

In [15]:
raw_data_generation = pd.read_csv('/home/nilima/Desktop/portfolio/probabilistic-energy-forecasting-ML/raw_data/Actual_generation_202403010000_202603020000_Hour.csv', sep=";")
display(raw_data_generation.head())
print(raw_data_generation.columns)

,Start date,End date,Biomass [MWh] Calculated resolutions,Hydropower [MWh] Calculated resolutions,Wind offshore [MWh] Calculated resolutions,Wind onshore [MWh] Calculated resolutions,Photovoltaics [MWh] Calculated resolutions,Other renewable [MWh] Calculated resolutions,Nuclear [MWh] Calculated resolutions,Lignite [MWh] Calculated resolutions,Hard coal [MWh] Calculated resolutions,Fossil gas [MWh] Calculated resolutions,Hydro pumped storage [MWh] Calculated resolutions,Other conventional [MWh] Calculated resolutions
0,"Mar 1, 2024 12:00 AM","Mar 1, 2024 1:00 AM","4,235.50","1,821.25","5,285.75","15,712.25",3.00,120.75,-,"8,705.75","2,809.50","6,887.75",21.50,"1,864.00"
1,"Mar 1, 2024 1:00 AM","Mar 1, 2024 2:00 AM","4,201.25","1,844.50","5,180.75","15,029.00",3.25,121.00,-,"8,255.25","2,784.25","6,396.00",50.75,"1,814.50"
2,"Mar 1, 2024 2:00 AM","Mar 1, 2024 3:00 AM","4,167.75","1,792.75","5,542.25","14,791.50",3.00,121.50,-,"8,141.25","2,770.00","6,075.50",11.75,"1,806.25"
3,"Mar 1, 2024 3:00 AM","Mar 1, 2024 4:00 AM","4,163.75","1,812.75","5,914.50","14,723.50",3.25,121.00,-,"8,194.00","2,731.25","6,089.50",2.75,"1,837.00"
4,"Mar 1, 2024 4:00 AM","Mar 1, 2024 5:00 AM","4,213.50","1,854.25","5,981.00","14,873.25",3.25,121.00,-,"8,283.25","2,770.00","6,522.75",39.00,"1,828.75"

Index(['Start date', 'End date', 'Biomass [MWh] Calculated resolutions',
       'Hydropower [MWh] Calculated resolutions',
       'Wind offshore [MWh] Calculated resolutions',
       'Wind onshore [MWh] Calculated resolutions',
       'Photovoltaics [MWh] Calculated resolutions',
       'Other renewable [MWh] Calculated resolutions',
       'Nuclear [MWh] Calculated resolutions',
       'Lignite [MWh] Calculated resolutions',
       'Hard coal [MWh] Calculated resolutions',
       'Fossil gas [MWh] Calculated resolutions',
       'Hydro pumped storage [MWh] Calculated resolutions',
       'Other conventional [MWh] Calculated resolutions'],
      dtype='object')